config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'messages/create'
  get 'messages/destroy'
  get "signin" => "sessions#new"
  post "signin" => "sessions#create"
  delete "signout" => "sessions#destroy"
  
  get "signup" =>  "users#new"
  resources :users, except: [:new]
  resources :messages
  resources :chatroom, except: [:index]
  
  root "chatroom#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord

  has_many :messages
  has_many :users, through: :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true

  has_secure_password
  has_one_attached :avatar
  has_many :messages
  has_many :chatrooms, through: :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :isloggedIn?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def isloggedIn?
    !!current_user
  end

  def require_user
    if !isloggedIn?
      flash[:alert] = "You are not logged in, Please signin to chat"
      redirect_to signin_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

  def index
    @chatrooms = Chatroom.all
    @chatroom = Chatroom.find_by(id: params[:id])
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @chatrooms = Chatroom.all
    render 'index'
  end

  def new

  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :require_user

  def index
    @messages = Message.all
  end

  def create
    @message = current_user.messages.new(message_params)
    @message.save
      redirect_to request.referrer
  end

  def destroy
  end

  private

  def message_params
    params.require(:message).permit(:body, :chatroom_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])

    if user && user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Signed in successfully"
      redirect_to root_path
    else
      flash.now[:alert] = "Invalid sigin details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Signed out successfully"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :create, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User created successfully"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit 
  end

  def update
    
    if @user.update(user_params)
      flash[:notice] = "User updated successfully"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "User account deleted successfully"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/_form.html.erb
<%= form_with(model: chatroom, local: true) do |form| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
        <% chatroom.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3 text-white">
    <%= form.label "Add a new room" %>
    <%= form.text_field :name, class: 'form-control', placeholder: "Room name" %>
  </div>

  <%= form.submit "Add", class: "btn btn-outline-primary btn-block text-white" %>
<% end %>

app/views/chatroom/index.html.erb
<div class="w-1/4 bg-black-100 p-4">
  <p class="text-white">Hello, <%=current_user.username %> </p>
</div>
<div class="flex flex-row">
  <div class=" my-4 border-gray-300 ">
    <div class="navbar h-[100vh] w-[6rem] border-gray-800 border-r-[3px] flex flex-col justify-between items-center pt-5 pb-5">
      <div class="flex flex-col items-center ">
        <% @chatrooms.each do |chatroom| %>
          <%= link_to chatroom_path(chatroom) do %>
            <h2 class=" bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4"><%= chatroom.name %></h2>
          <% end %>
        <% end %> 
      </div>
    </div>
  </div>

  <div class=" w-3/4 p-4 ">
    <% if @chatroom.present? %>
      <div class="bg-white w-full ">
        <nav class="flex flex-col justify-between bg-gray-800 mb-4">
          <div class="text-lg font-semibold text-white ml-4">
            <b><%= @chatroom.name %></b>
          </div>
          <small class="text-gray-400 ml-2"><%= @chatroom.users.uniq.count %> Members</small>
        </nav>
        <div class="flex flex-col space-y-4">
          <% @chatroom.messages.each do |message| %>
            <div class="flex <%= 'justify-end' if message.user == current_user %>">
              <div class="flex flex-col space-y-1 <%= message.user == current_user ? 'items-end' : 'items-start' %>">
                <div class="rounded-xl p-2 px-4 <%= message.user == current_user ? 'bg-blue-500 text-white' : 'bg-gray-200' %>">
                  <%= message.body %>
                </div>
                <% if message.user != current_user %>
                  <div class="text-sm font-low text-gray-500 ml-2"> 
                    <%= message.user.username %> 
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>



        <div class=" bottom-0 mb-4">
          <%= render 'messages/form', message: Message.new, room: @room %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_message.html.erb
<style>
    .skill-text {
        display: block;
        font-size: 12px;
        font-weight: 500;
    }

    .skill-layout {
        width: 100%;
        height: 6px;
        border-radius: 7px;
    }


    .skill-filled {
        width: 100%;
        height: 100%;
        border-radius: 7px;
        display: block;
        position: relative;
        animation: skillBar 1.5s ease-in-out forwards;

    }


    @keyframes skillBar {
        0% {
            width: 0;

        }

    }
</style>

<div class="w-[95%]">
    <% flash.each do |name, msg|%>
        <div class="w-[18rem] inline-block bg-white pt-3 m-2 rounded absolute top-2 left-3" id="msgblock">
            <p class="message p-2 font-semibold text-black font-xl ">
                <i class="fa fa-check-circle mr-1 <%= name == "alert" ? "text-red-500" : "text-green-500" %>"
                    aria-hidden="true"></i>
                <%=msg%>
            </p>
            <div class="skill-box mt-2">
                <div class="skill-layout">
                    <div class="skill-filled <%= name == "alert" ? "bg-red-500" : "bg-green-500" %>">
                    </div>
                </div>
            </div>

            <% end %>
        </div>







        <script>
            setTimeout(() => {
                document.getElementById("msgblock").style.display = 'none'
            }, 1500)
        </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messenger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
  </head>

  <body  class="w-full m-auto bg-[#121214] p-4">
    <%= render "layouts/message" %>
    <main class="">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation" class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 mb-4">
      <h2 class="font-semibold"><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul class="list-disc pl-5">
        <% message.errors.full_messages.each do |error_message| %>
          <li><%= error_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <input type="hidden" name="message[chatroom_id]" value="<%= @chatroom.id %>">
  
  <div class="flex items-center">
    <input type="text" name="message[body]" placeholder="Type your message here..." class="flex-grow p-2 border border-gray-300 rounded-l-lg focus:ring focus:ring-blue-200 mr-2">
    <input type="submit" value="Add Message" class="bg-blue-500 text-white px-4 py-2 rounded-r-lg hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-200">
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %>">
  <!-- <p><%= time_ago_in_words(message.created_at) %> ago</p> -->
  <div class="flex flex-col">
  <div class="flex items-center justify-between mb-1.5" style="width:fit-content">
  <span class="text-[.9rem] text-gray-400"><%= message.created_at.strftime("%l:%M %P") %></span>
  <i class="fa fa-ellipsis-h cursor-pointer text-[.9rem] text-gray-400 ml-3" aria-hidden="true"></i>
</div>

<% unless message.group.is_private %>
<span class="text-[#cfcecea9] text-[.9rem] font-semibold mb-2">
  @<%= message.user.username %>
</span>
<% end %>
  <div class="message-box msg-<%= message.user.id %> ">
        <div>
          <P>
            <%= message.body %>
              <p>
        </div>
  </div>
  </div>  
</div>

app/views/messages/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Messages#create</h1>
  <p>Find me in app/views/messages/create.html.erb</p>
</div>

app/views/messages/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Messages#destroy</h1>
  <p>Find me in app/views/messages/destroy.html.erb</p>
</div>

app/views/messages/index.html.erb
<h1 class="text-white">Messages</h1>
</br>

<% @messages.each do |msg| %>
  <div class="flex text-white">
    <b><%= msg.user.username %>: </b>
    <p class="ml-1"><%= msg.body %></p>
  </div>
<% end %>

<div class="message-form">
  <%= form_with( model: @message, data:{turbo: false}, local: true, class:"form_con flex flex-col") do |form| %>
    <%=form.text_field :body %>
    <%= form.submit "send",class:"text-black bg-white" %>
  <% end %>
</div>

app/views/users/create.html.erb
<div>
  <h1 class="font-bold text-4xl text-white">Users#create</h1>
  <p>Find me in app/views/users/create.html.erb</p>
</div>

app/views/users/edit.html.erb
<div class="w-[95%] h-[100vh] flex items-center flex-col justify-center relative">
  <div class="sign_form w-[90%] md:w-[60%] lg:w-[40%] bg-[#1a1819] py-10 px-5 border-solid border-2 border-gray-800 rounded-lg">

    <%= form_with( model: @user, data:{turbo: false}, local: true, class:"form_con flex flex-col") do |form| %>
      <div class="grid grid-cols-2 gap-4">
        <div class="input-box flex flex-col mt-4">
          <%= form.text_field :username, placeholder:"Enter new username", class:"text-gray-300 bg-[#1c1c1c] p-3 outline-none border-solid border-2
              border-gray-800 rounded-lg text-gray-200" %>
        </div>
        <div class="input-box flex flex-col mt-4">
          <%= form.password_field :password, placeholder:"Enter new password", class:"text-gray-300 bg-[#1c1c1c] p-3 outline-none border-solid border-2
              border-gray-800 rounded-lg text-gray-200 password-field" %>
        </div>
        <div class="input-box flex flex-col mt-4">
          <%= form.password_field :password_confirmation, placeholder:"Confirm new password", class:"text-gray-300 bg-[#1c1c1c] p-3 outline-none border-solid
              border-2 border-gray-800 rounded-lg text-white password-field" %>
        </div>

        <div class="input-box flex flex-col mt-3">
            <div class="mt-2 flex items-center">
              <%= image_tag("avatar.png",class:"w-[35px] mr-2") %>
                <label htmlFor="file-input"
                      className="ml-5 flex items-center justify-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50">
                  <span
                      class="bg-[#1c1c1c] text-white py-1.5 px-1 border-solid border-2 border-gray-800 rounded-lg cursor-pointer">Upload
                      image</span>
                  <%= form.file_field :avatar,class:"hidden"%>
                </label>
            </div>
        </div>

        <div class="input-box flex items-center">
          <input type="checkbox" name="pwd" id="pwd"
              class="mr-2  w-4 h-4 rounded-lg checked:bg-blue-500 focus:outline-none focus:ring-opacity-50 cursor-pointer"
              onclick="togglePasswordVisibility()" />
          <label for="pwd" class="text-white text-lg font-semibold">Show password</label>
        </div>
      </div>  



      <div class="input-box flex flex-col mt-4">
          <%= form.submit "Update" , class:"text-white text-lg bg-blue-700 hover:bg-blue-900 font-semibold
              pt-3 pb-3 rounded-lg ease-out duration-300 cursor-pointer"%>
      </div>
    <% end %>

    <div class="flex m-auto items-center mt-6">
        <h4 class="text-white font-normal text-lg">Go back to</h4>
        <%=link_to "Profile",user_path(@user), class:"text-blue-600 pl-2 font-bold text-lg" %>
    </div>
  </div>
</div>  

app/views/users/index.html.erb
<h1 class="text-white">Users</h1>


<% @users.each do |u| %>
  <div class="flex text-white">
    <b><%= link_to u.username, user_path(u) %></b>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="w-[95%] h-[100vh] flex items-center flex-col justify-center relative">
  <div class="sign_form w-[90%] md:w-[60%] lg:w-[40%] bg-[#1a1819] py-10 px-5 border-solid border-2 border-gray-800 rounded-lg">

    <ul class="text-white">
      <% if @user.errors.any? %>
      <div class="p-3 border-solid border-2 bg-red-400 border-red-800 rounded-lg">
        <% @user.errors.full_messages.each do |msg| %>
          <% if msg=="Username can't be blank" %>
            <li>Please enter your username</li>
            <% elsif msg=="Password confirmation doesn't match Password" %>
              <li>Your password does not match</li>
              <% elsif msg=="Username is too short (minimum is 6 characters)" %>
                <li>Password should exceed 5 characters</li>
                <% elsif msg=="Password can't be blank" %>
                  <li>Please enter password</li>
                  <% else %>
                    <li>
                      <%= msg %>
                    </li>
                    <% end %>
                      <% end %>
                    </div>
                        <% end %>
    </ul>

    <h2 class="mt-1 text-center text-3xl font-bold text-white">
      Signup
    </h2>
    <%= form_with( model: @user, data:{turbo: false}, local: true, class:"form_con flex flex-col") do |form| %>
      <div class="input-box flex flex-col mt-4">
        <%= form.label :username,class:"text-white font-semibold text-lg mb-3" %>
          <%= form.text_field :username,class:"bg-[#1c1c1c] p-3 outline-none border-solid border-2 border-gray-800 rounded-lg text-gray-200" %>
      </div>
      <div class="input-box flex flex-col mt-4">
        <%= form.label :email,class:"text-white font-semibold text-lg mb-3" %>
          <%= form.email_field :email,class:"bg-[#1c1c1c] p-3 outline-none border-solid border-2 border-gray-800 rounded-lg text-gray-200" %>
      </div>
      <div class="input-box flex flex-col mt-4">
        <%= form.label :password, class:"text-white font-semibold text-lg mb-3", id:"p-input" %>
        <%= form.password_field :password, class:"bg-[#1c1c1c] p-3 outline-none border-solid border-2 border-gray-800 rounded-lg text-gray-200 password-field" %>
      </div>
      <div class="input-box flex flex-col mt-4">
        <%= form.label :Confirm_Password,class:"text-white font-semibold text-lg mb-3" %>
        <%= form.password_field :password_confirmation,class:"bg-[#1c1c1c] p-3 outline-none border-solid border-2 border-gray-800 rounded-lg text-white password-field"   %>
      </div>

      <div class="input-box flex items-center mt-4">
        <input type="checkbox" name="pwd" id="pwd" class="mr-2  w-4 h-4 rounded-lg checked:bg-blue-500 focus:outline-none focus:ring-opacity-50 cursor-pointer" onclick="togglePasswordVisibility()"/>
        <label for="pwd" class="text-white text-lg font-semibold">Show password</label>
      </div>

      <div class="input-box flex flex-col mt-3">
        <div class="mt-2 flex items-center">
          <%= image_tag("avatar.png",class:"w-[35px] mr-2") %>
          <label
            htmlFor="file-input"
            className="ml-5 flex items-center justify-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50">
            <span class="bg-[#1c1c1c] text-white py-1.5 px-1 border-solid border-2 border-gray-800 rounded-lg cursor-pointer">Upload image</span>
            <%= form.file_field :avatar,class:"hidden"%>
          </label>
        </div>
      </div>

      <div class="input-box flex flex-col mt-4">
          <%= form.submit "Sign Up", class:"text-white text-lg bg-blue-700 hover:bg-blue-900 font-semibold pt-3 pb-3 rounded-lg ease-out duration-300 cursor-pointer"%>
        </div>
            <% end %>

            <div class="flex items-center mt-4">
              <h4 class="text-white font-normal text-lg">Already have an account?</h4>
              <%=link_to "Sign In" ,signin_path,class:"text-blue-600 pl-2 font-bold text-lg" %>
            </div>

  </div>
</div>

<script>
  function togglePasswordVisibility() {
    var passwordFields = document.querySelectorAll(".password-field");

    passwordFields.forEach(function(field) {
      if (field.type === "password") {
        field.type = "text";
      } else {
        field.type = "password";
      }
    });
  }
</script>

app/views/users/show.html.erb
<div class="w-[95%] h-[100vh] flex items-center flex-col justify-center relative m-auto">
    <div
        class="sign_form w-[90%] md:w-[60%] lg:w-[44%] bg-[#1a1819] py-10 px-5 border-solid border-2 border-gray-800 rounded-lg m-auto">


        <h2 class="mt-1 text-center text-3xl font-bold text-white">
            Profile
        </h2>
        <p class="mt-1 text-center text-[1.1rem] font-normal text-white">Welcome to your personal profile</p>
        <div class="w-[100%] flex flex-col py-8">
            <div class="m-auto w-[4rem] h-[4rem] rounded-full overflow-hidden">
                <% if @user&.avatar&.attached? %>
                    <%= image_tag(@user.avatar , class:"w-full h-full")%>
                        <% else %>
                            <%= image_tag('avatar.png' , class:"w-full h-full") %>
                                <%end%>
            </div>


    </div>
    <div class="w-auto flex items-center justify-center mb-4">
    <h2 class="p-1 text-gray-100 text-xl font-bold border-solid border-2 border-gray-800 rounded-lg">@<%= @user&.username %></h2>
    <div class="ml-3 flex items-center">
    <i class="fa fa-sign-out text-blue-500" aria-hidden="true"></i>
    <span><%= link_to 'Logout', signout_path,
     data:{turbo_method: :delete, turbo_confirm: "Click ok to continue to logout"},class:"ml-1 text-blue-500" %></span>
    </div>
</div>
    <!-- nav links -->

    <div class="w-[90%] md:w-full grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-0 m-auto">
        <div class="link flex items-center">
            <%= link_to root_path,class:"text-gray-100" do %>
            <i class="fa fa-comments ml-1" aria-hidden="true"></i>
            <%="Chats" %>
            <% end %>
        </div>
        <div class="link flex items-center">
          <%= link_to root_path,class:"text-gray-100" do %>
          <i class="fa fa-users ml-1" aria-hidden="true"></i>
          <%="Groups" %>
          <% end %>
      </div>
      <div class="link flex items-center">
        <%= link_to edit_user_path(@user),class:"text-gray-100" do %>
        <i class="fa fa-pencil-square" aria-hidden="true"></i>
        <%="Edit profile" %>
        <% end %>
    </div>

    <div class="link flex items-center">
      <%= link_to user_path(@user),data:{turbo_method: :delete, turbo_confirm: "Click ok to continue"},class:"text-red-500 " do %>
      <i class="fa fa-trash" aria-hidden="true"></i>
      <%="Delete account" %>
      <% end %>
  </div>

    </div>

    </div>
</div>



<script>
  function togglePasswordVisibility() {
    var passwordFields = document.querySelectorAll(".password-field");

    passwordFields.forEach(function(field) {
      if (field.type === "password") {
        field.type = "text";
      } else {
        field.type = "password";
      }
    });
  }
</script>